# SITE CONFIGURATION
title: Tour De Burrito # your site title
author: RemoteControlledBacon # You :P
description: > # Meta description of Homepage
  A new type of site that will help you find the best burrito in each town.
baseurl: "/sleek" # the subpath of your site, e.g. /blog
url: "https://janczizikow.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    #- https://twitter.com/NAME
    #- https://www.facebook.com/NAME
    #- https://www.linkedin.com/in/NAME
    #- https://github.com/NAME
    #- https://keybase.io/NAME

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
   A site where burrito enthusiasts can meet and eat
   Coming Soon!

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

#email: your-email@domain.com # email for form submission

#twitter_username: NAME # replace with your_twitter_username or comment to remove link from footer
github_username:  RemoteControlledBacon # replace with your_github_username or comment to remove link from footer
#instagram_username: NAME # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
